version: "3.8"
services:
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/amazon_clone_copy
      - JWT_SECRET=supersecret
      - FRONTEND_PATH=/usr/src/app/src/frontend
    depends_on:
      - mongo
  mongo:
    image: mongo:6.0
    restart: always
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
