version: "3.8"
services:
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/amazon_clone_copy
      - JWT_SECRET=supersecret
      - FRONTEND_PATH=/usr/src/app/src/frontend
    depends_on:
      - mongo
    restart: always
    command: ["node", "src/start.js"]
  mongo:
    image: mongo:6.0
    restart: always
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD-SHELL", 'mongo --eval "db.adminCommand(''ping'')" || exit 1']
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  mongo-data:
